### ISSUE TITLE
False positives when providing default values in destructuring assignment in function parameters

### ISSUE THREAD

**Issue by lekkas** [za-creature/coffeescope#21]
Hi,

Discovered a new one:

**coffeelint.json**

``` json
{
    "check_scope": {
      "module": "coffeescope2",
      "undefined": true,
      "unused_variables": true
    }
}
```

**coffeescript snippet**

``` coffeescript
fn = ({ property = false }) -> property
fn()
```

**result:**

```
  ⚡ test.coffee
     ⚡ #1: Undefined identifier "property".
```

**Comment by za-creature** [comment]
Ref #17 #18

Hope this wraps up the 'destructured defaults' list of issues. Released in 0.3.6

Thanks for the report!

**Comment by lekkas** [comment]
Cheers @za-creature !

**Comment by lekkas** [comment]
Hey @za-creature,

Reporting one more false positive that is not caught by ca886d7: 

```
({ property = {} }) -> property
```

**Comment by za-creature** [comment]
You're killing me here :)

**Comment by za-creature** [comment]
Re-released as 0.3.7

**Comment by lekkas** [comment]
You are incredibly fast in your replies :)

Didn't mean to overwhelm you with this, these come as we go and I open/update issues as soon as I find them so that they don't slip through the cracks - no rush, really.

We should lobby to get `coffeescope2` shipped by default in `coffeelint` :D

**Comment by za-creature** [comment]
Oh, no worries, I fully appreciate the reports.

This was actually a single bug that I fixed incorrectly a bunch of times, so I was just frustrated that I didn't think to test it more thoroughly the first time; it would've saved you some time :)

As for your second suggestion, [that was the original idea](https://github.com/clutchski/coffeelint/issues/551), but it was met with underwhelming interest so I postponed the idea for a while. Upon having a chance to [look into coffeelint's internals](https://github.com/clutchski/coffeelint/pull/552), I'm not sure adding more stuff into its core is the best of ideas:

A lot of it could use rewriting, and it is my impression that the maintainers are just keeping it on life support for the sake of rails. I would fork the whole thing and try to redesign certain aspects of it (I think the biggest gain would be to provide a mixed AST/Token linter, to enable easier implementation of rules like 'spaces around = unless assigning defaults in a method'), but I'm worried that there's not enough interest in coffeelint or for that matter coffeescript itself ([redux](https://github.com/michaelficarra/CoffeeScriptRedux) was a tough pill to swallow) for that project to ever become useful.

The primary reason I'm replying so fast to issues is that I'm late to the coffeescript party and I'm doing my best to revive it. In this sense, I tried to tackle one of the most controversial aspects of the language: variable scoping. While I've been met with _some_ interest in doing this, I'm worried that it's not enough and its current leadership is [doing little](https://github.com/jashkenas/coffeescript/issues/4206) to help organize the (potentially inexistent) masses.

As such, I fear that this may be a losing battle, which really sucks because while ES2016 is definitely an improvement, I believe it will never be a _good_ language unless it ditches backwards compatibility.
