### ISSUE TITLE
A general question about coffeescope2

### ISSUE THREAD

**Issue by katspaugh** [za-creature/coffeescope#26]
Hi, Radu!

What are the main differences from [coffeelint-undefined-variables](https://github.com/AsaAyers/coffeelint-undefined-variables)?

From what I've gathered from the readme, your plugin has more options. Any other advantages?

Thanks!

**Comment by za-creature** [comment]
Hi, uh... stranger!

You've already seen https://github.com/clutchski/coffeelint/issues/415 so you should know half the context by now.

This project exists because the original coffeescope was never completed and the author made [his position about coffeescript](https://github.com/AsaAyers/coffeescope#coffeescript-is-terrible) clear (for comparison, [here's mine](https://github.com/clutchski/coffeelint/issues/551#issuecomment-188931941)). So I guess the biggest advantage I can think of is the fact that coffeescope2 is actively being developed, whereas you are likely to be on your own with the older package.

Feature-wise, coffeescope2 does indeed have more options, but that can be a mixed blessing at times because given limited resources, I had to trade-off implementation purity for project usefulness which is never a great sign for a project's health.

I'll leave this open in case you have follow-ups.

**Comment by katspaugh** [comment]
Thanks for the reply!

I've replaced `coffeelint-undefined-variables` with `coffeescope2` in one project and I already see some things that the previous plugin didn't catch. Actually tons of overwritten variables and some unused ones. It's great that your plugin has control over which things to warn about.

Great job and please keep it up!

**Comment by za-creature** [comment]
Will do, thanks for the interest!
